package seed.servlet;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class LoginServlet
 */
public class LoginServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public LoginServlet() {
        super();
        
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		
		response.getWriter().append("Served at: ").append(request.getContextPath());
		
		 String txtunm = request.getParameter("txtname");
		 String txtpwd = request.getParameter("txtpassword");
		    
		 PrintWriter out=response.getWriter();
		 	  
		  if(txtunm.equals("Anupam") && txtpwd.equals("anu")){
			//out.write(" Valid User "); //response generated by LoginServlet
			  
			//server-side redirect
			RequestDispatcher rd1=getServletContext().getRequestDispatcher("/WelcomeServlet");
			rd1.forward(request, response); // go to another servlet in same web application
			  // whenever we do  RequestDispatching it includes resources
		  }
		  else{
			  RequestDispatcher rd2=getServletContext().getRequestDispatcher("/Login.html");
			  out.write(" Invalid User ");
			  out.write(" Please try again ... ");
			  rd2.include(request, response); // go back to html in same web application
		  }
	}
	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		
		doGet(request, response);
	}

}
